# Generated by Django 4.0.3 on 2022-03-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_user_id', models.CharField(max_length=32)),
                ('human_name', models.CharField(max_length=64)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('course', models.TextField()),
                ('approved', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_user_id', models.CharField(max_length=32)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('channel', models.CharField(max_length=32)),
                ('proof', models.TextField()),
            ],
        ),
    ]
