# Generated by Django 4.0.3 on 2022-03-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_transcript_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterequest',
            name='approved',
            field=models.TextField(),
        ),
    ]
