# Generated by Django 4.0.3 on 2022-04-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_certificaterequest_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
