# Generated by Django 4.0.3 on 2022-04-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_transcript_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterequest',
            name='approved',
            field=models.BooleanField(),
        ),
    ]
