# Generated by Django 4.0.3 on 2022-04-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_certificaterequest_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterequest',
            name='approved',
            field=models.CharField(choices=[('ACC', 'Accepted'), ('REJ', 'Rejected'), ('UNK', 'Unknown')], default='UNK', max_length=3),
        ),
    ]
