# Generated by Django 4.2.1 on 2023-05-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_certificaterequest_approved"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slack_channel_id", models.CharField(max_length=32)),
                ("message", models.TextField()),
                ("scheduled_for", models.DateTimeField()),
                ("sent", models.DateTimeField(null=True)),
            ],
        ),
    ]
