# Generated by Django 4.2.1 on 2023-05-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_scheduledmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledmessage",
            name="sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
