# Generated by Django 4.2.1 on 2023-05-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_scheduledmessage_sent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gratitude",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("date", models.DateTimeField()),
                ("slack_channel_human", models.CharField(max_length=64)),
            ],
        ),
    ]
