# Generated by Django 4.2.1 on 2023-06-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_rename_slack_channel_human_gratitude_slack_channel_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificaterequest",
            name="human_name_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
